name: linuxptp
base: core22
summary: Linux Precision Time Protocol (PTP)
description: |
  Snap packaging for linuxptp,
  an implementation of the Precision Time Protocol (PTP) according to IEEE standard 1588 for Linux.
license: GPL-2.0-or-later
adopt-info: linuxptp

grade: devel
confinement: strict

parts:
  local:
    plugin: nil
    source: snap/local
    override-build: |
      CONF=$SNAPCRAFT_PART_INSTALL/etc
      BIN=$SNAPCRAFT_PART_INSTALL/bin
      mkdir -p $CONF
      cp -v etc/* $CONF/
      mkdir -p $BIN
      cp -v bin/* $BIN/

  linuxptp:
    after: [local]
    plugin: make
    source-type: git
    source: https://git.code.sf.net/p/linuxptp/code
    source-tag: v4.4
    source-depth: 1
    # make-parameters: 
    override-build: |
      DOC=$CRAFT_PART_INSTALL/usr/share/doc
      mkdir -p $DOC
      cp COPYING $DOC/

      CONF=$SNAPCRAFT_PART_INSTALL/etc
      mkdir -p $CONF
      cp -v configs/* $CONF

      # Replace /var/run with /run/snap.linuxptp in config
      sed -i 's/\/var\/run/\/run\/snap.linuxptp/g' $CONF/default.cfg

      # Replace hardcoded /var/run with /run/snap.linuxptp
      sed -i 's/\/var\/run/\/run\/snap.linuxptp/g' \
          configs/default.cfg \
          config.c \
          phc2sys.c \
          pmc.c \
          timemaster.c \
          ts2phc.c \
          tz2alt.c

      craftctl set version="$(git describe --tags | sed s/v//)+snap"
      
      craftctl default

apps:
  hwstamp-ctl: # renamed to bypass character restrictions
    command: usr/local/sbin/hwstamp_ctl
    plugs:
      - network-bind
      - network-control
  nsm:
    command: usr/local/sbin/nsm
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
  phc-ctl: # renamed to bypass character restrictions
    command: usr/local/sbin/phc_ctl
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      # Access to system date and time
      - time-control
      # Access to system logs and data
      - system-backup
      - log-observe

  phc2sys:
    command: usr/local/sbin/phc2sys
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      # Access to system date and time
      - time-control
      # Access to system logs and data
      - system-backup
      - log-observe

  pmc:
    command: usr/local/sbin/pmc
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
  ptp4l:
    command: usr/local/sbin/ptp4l
    plugs:
      - network
      - network-bind
      - network-control
      # Access to system date and time
      - time-control
      # Access to PTP subsystem and files
      - ptp

  timemaster:
    command: usr/local/sbin/timemaster
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp

  ts2phc:
    command: usr/local/sbin/ts2phc
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp
      # Access to system date and time
      - time-control
      # Access to read system logs and data
      - system-backup
      - log-observe
  tz2alt:
    command: usr/local/sbin/tz2alt
    plugs:
      - network-bind
      - network-control
      # Access to PTP subsystem and files
      - ptp

  create-run-dir-service:
    # Create the expected run directory on install and after each boot
    command: bin/create-run-dir.sh
    daemon: oneshot
